### PR TITLE
113 adjust `toggle_slider` ranges

### PR DESCRIPTION
**Pull request by m7pr**
This is solution for #133 

`toggle_slider` is a component that is a sliderInput that can be toggled to become a numericInput.

image

image

The PR fixes the issue with ranges on sliderInput that should be adjusted based on numericInput.

So if slider had ranges min_sliderInput and max_sliderInput and values for numercInput are changed, so that min(numercInput) is lower than min_sliderInput or max(numercInput) is greater than max_sliderInput, then `min_sliderInput` or `max_sliderInput` should be extended for new ranges.

# Example 1

min_sliderInput, max_sliderInput - on start 0, 55 

image

hence numericInput on start 0, 55

image

numericInput changes to -5, 65

image

sliderInput changes to -5, 65

image

# Example 2

Continuation of the previous one, if you change numericInput from -5, 65

image

to 4, 45

image

sliderInput is reset (the min and max) to original 0, 55 but values are set to 4, 45

image

### CODE REVIEW

**Review by donyunardi — CHANGES_REQUESTED** [review]
I still see the same problem.

I used the example code that's provided in [this comment](https://github.com/insightsengineering/teal.goshawk/issues/133#issuecomment-2396338015) and changed the "Select an X-Axis Biomarker" to "CRP". 

Is it because the range is too short?

image

**Comment by m7pr** [comment]
Hey @donyunardi the code that you linked to links to `tm_g_gh_boxplot`, and your print screen shows `tm_g_gh_lineplot`.
Can you share the code for `tm_g_gh_lineplot` that you used? Also, did you run the check on the feature branch?

**Comment by m7pr** [comment]
> I still see the same problem.

What problem do you see? I would assume you show the state of `sliderInput` and `numericInput` to describe the problem. Here you only posted sliderInput. What the user really wanted is to get `sliderInput` adjusted once `numericInput` get's changes and exceeds the limits of `sliderInput`



https://github.com/user-attachments/assets/5894c8eb-0211-4dc9-81f2-aebea7c5d146

**Comment by m7pr** [comment]
Ah, ok I see. This issue is related to two things. The second thing are the ticks on slider that are non-unique. Will have a look at it as well

**Pull request merged**
