### PR TITLE
#219 add facet_scales to plot aesthetics menu

### LINKED ISSUE #219: tm_g_gh_spaghettiplot will have all x ticks and labels
### Feature description

**Request**: Is it possible to have the x ticks in red circles where there are no records (or data points) not displayed in the spaghetti plot? 

spaghetti_plot

**Observations**: The line plot with the same filter setting only displays x ticks where there are records (or data points).

line_plot

I also explored the source code of [tm_g_gh_spaghettiplot](https://code.roche.com/nest/insights-engineering/teal.goshawk/-/blob/main/R/tm_g_gh_spaghettiplot.R)  and [tm_g_gh_lineplot](https://code.roche.com/nest/insights-engineering/teal.goshawk/-/blob/main/R/tm_g_gh_lineplot.R) and found some differences between them which may cause the differences in spaghetti plot and line plot display just from my understanding. Not sure if they are the true cause. Please see two chunks of code below. Hope this is helpful. Thank you.
**_tm_g_gh_lineplot:_** subset the data based on xtick
```ruby
# Row 728-744
private_qenv <- teal.code::eval_code(
  object = private_qenv,
  code = bquote({
    keep_index <- which(.(xtick) %in% ANL[[.(xaxis)]])
    xtick <- (.(xtick))[keep_index] # extra parentheses needed for edge case, e.g. 1:5[keep_index]
    xlabel <- (.(xlabel))[keep_index]
  })
)

# Row 754
data = ANL[stats::complete.cases(ANL[, c(.(yaxis), .(xaxis))]), ],
```
**_tm_g_gh_spaghettiplot:_** doesn't do the subset 
```ruby
# Row 445-448
private_qenv <- teal.code::eval_code(
  object = private_qenv,
  code = bquote(xtick <- .(xtick))
)

# Row 472
data = ANL
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by m7pr**
Closes #219 

With this PR I extended `Plot Aesthetic Settings` foldable UI with an option to pass `scales` parameter to `ggplot2::facet_wrap`. This also required a change in https://github.com/insightsengineering/goshawk/pull/201

```{R}
library(dplyr)

# original ARM value = dose value
arm_mapping <- list(
  "A: Drug X" = "150mg QD",
  "B: Placebo" = "Placebo",
  "C: Combination" = "Combination"
)
set.seed(1)
ADSL <- goshawk::rADSL
ADLB <- goshawk::rADLB
var_labels <- lapply(ADLB, function(x) attributes(x)$label)
ADLB <- ADLB %>%
  dplyr::mutate(
    AVISITCD = dplyr::case_when(
      AVISIT == "SCREENING" ~ "SCR",
      AVISIT == "BASELINE" ~ "BL",
      grepl("WEEK", AVISIT) ~ paste("W", stringr::str_extract(AVISIT, "(?<=(WEEK ))[0-9]+")),
      TRUE ~ as.character(NA)
    ),
    AVISITCDN = dplyr::case_when(
      AVISITCD == "SCR" ~ -2,
      AVISITCD == "BL" ~ 0,
      grepl("W", AVISITCD) ~ as.numeric(gsub("[^0-9]*", "", AVISITCD)),
      TRUE ~ as.numeric(NA)
    ),
    AVISITCD = factor(AVISITCD) %>% reorder(AVISITCDN),
    TRTORD = dplyr::case_when(
      ARMCD == "ARM C" ~ 1,
      ARMCD == "ARM B" ~ 2,
      ARMCD == "ARM A" ~ 3
    ),
    ARM = as.character(arm_mapping[match(ARM, names(arm_mapping))]),
    ARM = factor(ARM) %>% reorder(TRTORD),
    ACTARM = as.character(arm_mapping[match(ACTARM, names(arm_mapping))]),
    ACTARM = factor(ACTARM) %>% reorder(TRTORD),
    ANRLO = 30,
    ANRHI = 75
  ) %>%
  dplyr::rowwise() %>%
  dplyr::group_by(PARAMCD) %>%
  dplyr::mutate(LBSTRESC = ifelse(USUBJID %in% sample(USUBJID, 1, replace = TRUE),
                                  paste("<", round(runif(1, min = 25, max = 30))), LBSTRESC
  )) %>%
  dplyr::mutate(LBSTRESC = ifelse(USUBJID %in% sample(USUBJID, 1, replace = TRUE),
                                  paste(">", round(runif(1, min = 70, max = 75))), LBSTRESC
  )) %>%
  ungroup()
attr(ADLB[["ARM"]], "label") <- var_labels[["ARM"]]
attr(ADLB[["ACTARM"]], "label") <- var_labels[["ACTARM"]]
attr(ADLB[["ANRLO"]], "label") <- "Analysis Normal Range Lower Limit"
attr(ADLB[["ANRHI"]], "label") <- "Analysis Normal Range Upper Limit"

# add LLOQ and ULOQ variables
ALB_LOQS <- goshawk:::h_identify_loq_values(ADLB)
ADLB <- dplyr::left_join(ADLB, ALB_LOQS, by = "PARAM")

app <- teal::init(
  data = teal.data::cdisc_data(
    teal.data::cdisc_dataset("ADSL", ADSL, code = "ADSL <- goshawk::rADSL"),
    teal.data::cdisc_dataset(
      "ADLB",
      ADLB,
      code = "set.seed(1)
              ADLB <- goshawk::rADLB
              var_labels <- lapply(ADLB, function(x) attributes(x)$label)
              ADLB <- ADLB %>%
                dplyr::mutate(AVISITCD = dplyr::case_when(
                    AVISIT == 'SCREENING' ~ 'SCR',
                    AVISIT == 'BASELINE' ~ 'BL',
                    grepl('WEEK', AVISIT) ~
                      paste('W', stringr::str_extract(AVISIT, '(?<=(WEEK ))[0-9]+')),
                    TRUE ~ as.character(NA)),
                  AVISITCDN = dplyr::case_when(
                    AVISITCD == 'SCR' ~ -2,
                    AVISITCD == 'BL' ~ 0,
                    grepl('W', AVISITCD) ~ as.numeric(gsub('[^0-9]*', '', AVISITCD)),
                    TRUE ~ as.numeric(NA)),
                  AVISITCD = factor(AVISITCD) %>% reorder(AVISITCDN),
                  TRTORD = dplyr::case_when(
                    ARMCD == 'ARM C' ~ 1,
                    ARMCD == 'ARM B' ~ 2,
                    ARMCD == 'ARM A' ~ 3),
                  ARM = as.character(arm_mapping[match(ARM, names(arm_mapping))]),
                  ARM = factor(ARM) %>% reorder(TRTORD),
                  ACTARM = as.character(arm_mapping[match(ACTARM, names(arm_mapping))]),
                  ACTARM = factor(ACTARM) %>% reorder(TRTORD),
                  ANRLO = 30,
                  ANRHI = 75) %>%
                  dplyr::rowwise() %>%
                  dplyr::group_by(PARAMCD) %>%
                  dplyr::mutate(LBSTRESC = ifelse(USUBJID %in% sample(USUBJID, 1, replace = TRUE),
                  paste('<', round(runif(1, min = 25, max = 30))), LBSTRESC)) %>%
                  dplyr::mutate(LBSTRESC = ifelse(USUBJID %in% sample(USUBJID, 1, replace = TRUE),
                  paste( '>', round(runif(1, min = 70, max = 75))), LBSTRESC)) %>%
                  ungroup
               attr(ADLB[['ARM']], 'label') <- var_labels[['ARM']]
               attr(ADLB[['ACTARM']], 'label') <- var_labels[['ACTARM']]
               attr(ADLB[['ANRLO']], 'label') <- 'Analysis Normal Range Lower Limit'
               attr(ADLB[['ANRHI']], 'label') <- 'Analysis Normal Range Upper Limit'
               ALB_LOQS <- goshawk:::h_identify_loq_values(ADLB)
               ADLB <- left_join(ADLB, ALB_LOQS, by = 'PARAM')",
      vars = list(arm_mapping = arm_mapping)
    ),
    check = FALSE
  ),
  modules = teal::modules(
    teal.goshawk::tm_g_gh_spaghettiplot(
      label = "Spaghetti Plot",
      dataname = "ADLB",
      param_var = "PARAMCD",
      param = choices_selected(c("ALT", "CRP", "IGA"), "ALT"),
      idvar = "USUBJID",
      xaxis_var = choices_selected(c("Analysis Visit Code" = "AVISITCD"), "AVISITCD"),
      yaxis_var = choices_selected(c("AVAL", "CHG", "PCHG"), "AVAL"),
      filter_var = choices_selected(
        c("None" = "NONE", "Screening" = "BASE2", "Baseline" = "BASE"),
        "NONE"
      ),
      trt_group = choices_selected(c("ARM", "ACTARM"), "ARM"),
      color_comb = "#39ff14",
      man_color = c(
        "Combination" = "#000000",
        "Placebo" = "#fce300",
        "150mg QD" = "#5a2f5f"
      ),
      hline_arb = c(60, 50),
      hline_arb_color = c("grey", "red"),
      hline_arb_label = c("default A", "default B"),
      hline_vars = c("ANRHI", "ANRLO", "ULOQN", "LLOQN"),
      hline_vars_colors = c("pink", "brown", "purple", "black"),
    )
  )
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}
```

image

### CODE REVIEW

**Comment by chlebowa** [comment]
I don't think it works:
image
facets set to `"free"`

There is a range slider that determines the Y axis scale - will that not preclude freeing the Y axis?

Also, I scales are not aesthetics, put the input somewhere else.

**Comment by m7pr** [comment]
@chlebowa thanks

> Also, I scales are not aesthetics, put the input somewhere else.

☝️ `scales` are in the same place as `facet_ncol` which determines `ncol` in `facet_wrap`. Also the Y-axis zoom is listed under this aesthetics part. I think adding `scales` next to other AXIS and GRID manipulators under the same area in which they existed should be fine.

**Comment by m7pr** [comment]
Thanks for checking the case with `AVISITCD` - it indeed doesn't remove `SCR` level where all `PCHG` are NAs.

```{R}
library(ggplot2)
ADLB %>%
  select(AVISITCD, PCHG, ARM) %>%
  ggplot(aes(x = AVISITCD, y = PCHG, col = ARM)) +
  geom_point()+
  facet_wrap(~ARM, scales = 'free_x')
```

Will double check that again

image

**Comment by m7pr** [comment]
Hey @chlebowa check-out this example. Below I created 3 datasets

```{R}
# removing missing levels from the plot with facet_scales
ADLB2 <- ADLB %>% 
  filter(!(ARM == 'Placebo' & AVISITCD == "SCR"))

ADLB3 <- ADLB %>%
  mutate(AVISITCD = case_when(
    ARM == 'Placebo' & AVISITCD  == "SCR" ~ NA_character_,
    TRUE ~ AVISITCD
  ))
```  

- ADLB - all rows
- ADLB2 - some rows filtered, hence some combination of `ARM and AVISITCD` do not exist in the data (ARM=facet, AVISITCD=x)
- ADLB3 - all rows, some combinations of `ARM and AVISITCD` do not exist in the data (ARM=facet, AVISITCD=x), but `ARM` exist for all datapoints, even though `AVISITCD` is NA

When I was testing this functionality, I actually tested situation of `ADLB2` where combination of `facet * x` did not exist in the dataset and could be removed. Check below plots to see difference in `PLACEBO` panel. I think `scales` does the trick for `ADLB2` - situation when combination of `facet*x` is missing from the dataset. And to get NAs removed from the plot IMHO one needs to apply filters in the filter panel to drop specific NAs from the data.


```{R}
> table(ADLB$ARM, ADLB$AVISITCD, useNA = 'always')
             
               BL SCR W 1 W 2 W 3 W 4 W 5 <NA>
  Combination 396 396 396 396 396 396 396    0
  Placebo     402 402 402 402 402 402 402    0
  150mg QD    402 402 402 402 402 402 402    0
  <NA>          0   0   0   0   0   0   0    0
> table(ADLB2$ARM, ADLB2$AVISITCD, useNA = 'always')
             
               BL SCR W 1 W 2 W 3 W 4 W 5 <NA>
  Combination 396 396 396 396 396 396 396    0
  Placebo     402   0 402 402 402 402 402    0
  150mg QD    402 402 402 402 402 402 402    0
  <NA>          0   0   0   0   0   0   0    0
> table(ADLB3$ARM, ADLB3$AVISITCD, useNA = 'always')
             
               BL SCR W 1 W 2 W 3 W 4 W 5 <NA>
  Combination 396 396 396 396 396 396 396    0
  Placebo     402   0 402 402 402 402 402  402
  150mg QD    402 402 402 402 402 402 402    0
  <NA>          0   0   0   0   0   0   0    0
```


full code is below, here is just a bit of comments

```{R}
library(ggplot2)
# FIRST PLOT
ADLB %>%
  select(AVISITCD, PCHG, ARM) %>%
  ggplot(aes(x = AVISITCD, y = PCHG, col = ARM)) +
  geom_point()+
  facet_wrap(~ARM, scales = 'free_x')

# SECOND PLOT
ADLB2 %>%
  select(AVISITCD, PCHG, ARM) %>%
  ggplot(aes(x = AVISITCD, y = PCHG, col = ARM)) +
  geom_point()+
  facet_wrap(~ARM, scales = 'free_x')

# THIRD PLOT
ADLB3 %>%
  select(AVISITCD, PCHG, ARM) %>%
  ggplot(aes(x = AVISITCD, y = PCHG, col = ARM)) +
  geom_point()+
  facet_wrap(~ARM, scales = 'free_x')
```

First plot
image

Second plot
image

Third plot
image

# FULL CODE

```{R}
library(goshawk)
library(stringr)

# original ARM value = dose value
arm_mapping <- list(
  "A: Drug X" = "150mg QD", "B: Placebo" = "Placebo", "C: Combination" = "Combination"
)
color_manual <- c("150mg QD" = "#000000", "Placebo" = "#3498DB", "Combination" = "#E74C3C")

ADLB <- goshawk::rADLB
var_labels <- lapply(ADLB, function(x) attributes(x)$label)
ADLB <- ADLB %>%
  mutate(AVISITCD = case_when(
    AVISIT == "SCREENING" ~ "SCR",
    AVISIT == "BASELINE" ~ "BL",
    grepl("WEEK", AVISIT) ~
      paste(
        "W",
        trimws(
          substr(
            AVISIT,
            start = 6,
            stop = str_locate(AVISIT, "DAY") - 1
          )
        )
      ),
    TRUE ~ NA_character_
  )) %>%
  mutate(AVISITCDN = case_when(
    AVISITCD == "SCR" ~ -2,
    AVISITCD == "BL" ~ 0,
    grepl("W", AVISITCD) ~ as.numeric(gsub("\\D+", "", AVISITCD)),
    TRUE ~ NA_real_
  )) %>%
  # use ARMCD values to order treatment in visualization legend
  mutate(TRTORD = ifelse(grepl("C", ARMCD), 1,
                         ifelse(grepl("B", ARMCD), 2,
                                ifelse(grepl("A", ARMCD), 3, NA)
                         )
  )) %>%
  mutate(ARM = as.character(arm_mapping[match(ARM, names(arm_mapping))])) %>%
  mutate(ARM = factor(ARM) %>%
           reorder(TRTORD)) %>%
  mutate(ANRLO = .5, ANRHI = 1) %>%
  rowwise() %>%
  group_by(PARAMCD) %>%
  mutate(LBSTRESC = ifelse(USUBJID %in% sample(USUBJID, 1, replace = TRUE),
                           paste("<", round(runif(1, min = .5, max = .7))), LBSTRESC
  )) %>%
  mutate(LBSTRESC = ifelse(USUBJID %in% sample(USUBJID, 1, replace = TRUE),
                           paste(">", round(runif(1, min = .9, max = 1.2))), LBSTRESC
  )) %>%
  ungroup()
attr(ADLB[["ARM"]], "label") <- var_labels[["ARM"]]
attr(ADLB[["ANRLO"]], "label") <- "Analysis Normal Range Lower Limit"
attr(ADLB[["ANRHI"]], "label") <- "Analysis Normal Range Upper Limit"

# add LLOQ and ULOQ variables
ADLB_LOQS <- goshawk:::h_identify_loq_values(ADLB)
ADLB <- left_join(ADLB, ADLB_LOQS, by = "PARAM")


# removing missing levels from the plot with facet_scales
ADLB2 <- ADLB %>% 
  filter(!(ARM == 'Placebo' & AVISITCD == "SCR"))

ADLB3 <- ADLB %>%
  mutate(AVISITCD = case_when(
    ARM == 'Placebo' & AVISITCD  == "SCR" ~ NA_character_,
    TRUE ~ AVISITCD
  ))

table(ADLB$ARM, ADLB$AVISITCD, useNA = 'always')
table(ADLB2$ARM, ADLB2$AVISITCD, useNA = 'always')
table(ADLB3$ARM, ADLB3$AVISITCD, useNA = 'always')

library(ggplot2)
ADLB %>%
  select(AVISITCD, PCHG, ARM) %>%
  ggplot(aes(x = AVISITCD, y = PCHG, col = ARM)) +
  geom_point()+
  facet_wrap(~ARM, scales = 'free_x')

ADLB2 %>%
  select(AVISITCD, PCHG, ARM) %>%
  ggplot(aes(x = AVISITCD, y = PCHG, col = ARM)) +
  geom_point()+
  facet_wrap(~ARM, scales = 'free_x')

ADLB3 %>%
  select(AVISITCD, PCHG, ARM) %>%
  ggplot(aes(x = AVISITCD, y = PCHG, col = ARM)) +
  geom_point()+
  facet_wrap(~ARM, scales = 'free_x')
```

**Comment by m7pr** [comment]
I remember about this
> There is a range slider that determines the Y axis scale - will that not preclude freeing the Y axis?
Will reply in the next comment

**Comment by chlebowa** [comment]
> I should also remember about [insightsengineering/goshawk#201 (comment)](https://github.com/insightsengineering/goshawk/pull/201#discussion_r1267965681)

I got ahead of myself about the validator. The input is independent of data nad there will always be a valid value, so input validation will not be necessary. Sorry about that. Now, `match.arg` on the other hand, should be there in my opinion.

**Comment by m7pr** [comment]
@chlebowa 

> There is a range slider that determines the Y axis scale - will that not preclude freeing the Y axis?

So yeah, `coord_cartesian` that sets Y axis is applied after `facet_wrap`. In a regular plot in `goshawk::g_spaghettiplot` `ylim` is set to `NA`s by default so it has no implication when `facet_scales` are used. On the other hand in `teal.goshawk::tm_g_gh_spaghettiplot` this is set by the module before the shiny app starts, hence it overwrites `facet_scales` for `free_y`. I guess, we can remove this option from UI and leave only - `fixed` and `free_x` for `facet_scales`

**Comment by chlebowa** [comment]
> I guess, we can remove this option from UI and leave only - `fixed` and `free_x` for `facet_scales`

How about making it a checkbox?

**Comment by m7pr** [comment]
@chlebowa oh yeah, now it makes sense if there is only 2 options now. Will update

**Comment by m7pr** [comment]
@chlebowa I just pushed the change. We have a checkboxInput for freeing X scales
image
image

**Pull request merged**
